using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace Problem2
{
    class Program
    {
        //Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
        //By starting with 1 and 2, the first 10 terms will be:  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        //By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

        static void Main(string[] args)
        {
            List<long> list = new List<long>();
            List<long> listEven = new List<long>();
            
            list.Add(1); list.Add(2);
            listEven.Add(2);

            long nr; 

            do
            {
                nr = list.Max() + list.ElementAt<long>(list.Count - 2);
                list.Add(nr);

                if (nr % 2 == 0)
                    listEven.Add(nr);
            }
            while (nr < 4000000);


            Console.WriteLine("{0}", listEven.Sum());

           Console.ReadKey();
        }
    }
}
